var symbolTemplate = {

	'countrycapital': {
		'fontSize': 12,
		'fontWeight': 'bold',
		'fontColor': '#000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'camps',
		'width': 11,
		'height': 11,
		'icon': './images/mapicons/CountryCapital.svg',
		'xOffset': 0,
		'yOffset': 0
	},

	'admin1capital': {
		'fontSize': 12,
		'fontWeight': 'normal',
		'fontColor': '#000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'camps',
		'width': 10,
		'height': 10,
		'icon': './images/mapicons/Admin1Capital.svg',
		'xOffset': 0,
		'yOffset': 0
	},

	'admin2capital': {
		'fontSize': 11,
		'fontWeight': 'normal',
		'fontColor': '#000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'camps',
		'width': 10,
		'height': 10,
		'icon': './images/mapicons/Admin2Capital.svg',
		'xOffset': -1,
		'yOffset': -0.5
	},

	'city': {
		'fontSize': 11,
		'fontWeight': 'normal',
		'fontColor': '#333333',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'camps',
		'width': 6,
		'height': 6,
		'icon': './images/mapicons/City.svg',
		'xOffset': -2,
		'yOffset': -0.5
	},

	'poi': {
		'fontSize': 11,
		'fontWeight': 'bold',
		'fontColor': '#333333',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'poi',
		'width': 6,
		'height': 6,
		'icon': './images/mapicons/POI.svg',
		'xOffset': -2,
		'yOffset': -0.5
	},

	'epicentre': {
		'fontSize': 12,
		'fontWeight': 'bold',
		'fontColor': '#7D0302',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'epicentre',
		'width': 14,
		'height': 14,
		'icon': './images/mapicons/epicentre.svg',
		'xOffset': 0,
		'yOffset': 0
	},
	// un office
	'office0': {
		'fontSize': 12,
		'fontWeight': 'bold',
		'fontColor': '#000000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'office0',
		'width': 20,
		'height': 20,
		'icon': './images/mapicons/UNOffice.svg',
		'xOffset': 4,
		'yOffset': 0
	},
	// regional office
	'office1': {
		'fontSize': 11,
		'fontWeight': 'bold',
		'fontColor': '#000000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'office1',
		'width': 17,
		'height': 17,
		'icon': './images/mapicons/Office1.svg',
		'xOffset': 2,
		'yOffset': 0
	},
	// branch office
	'office2': {
		'fontSize': 11,
		'fontWeight': 'bold',
		'fontColor': '#000000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'office2',
		'width': 15,
		'height': 15,
		'icon': './images/mapicons/Office2.svg',
		'xOffset': 2,
		'yOffset': 0
	},
	// sub office
	'office3': {
		'fontSize': 11,
		'fontWeight': 'bold',
		'fontColor': '#000000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'office3',
		'width': 15,
		'height': 15,
		'icon': './images/mapicons/Office3.svg',
		'xOffset': 2,
		'yOffset': 0
	},
	// field office
	'office4': {
		'fontSize': 11,
		'fontWeight': 'bold',
		'fontColor': '#000000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'office4',
		'width': 12,
		'height': 12,
		'icon': './images/mapicons/Office4.svg',
		'xOffset': 0,
		'yOffset': 0
	},
	// temporary office
	'office5': {
		'fontSize': 11,
		'fontWeight': 'bold',
		'fontColor': '#000000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'office5',
		'width': 12,
		'height': 12,
		'icon': './images/mapicons/Office5.svg',
		'xOffset': 0,
		'yOffset': 0
	},
	'camp': {
		'fontSize': 11,
		'fontWeight': 'bold',
		'fontColor': '#000000',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'camp',
		'width': 13,
		'height': 13,
		'icon': './images/mapicons/Camps.svg',
		'xOffset': 0,
		'yOffset': 0
	},
	'location': {
		'fontSize': 10,
		'fontWeight': 'bold',
		'fontColor': '#555555',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'location',
		'width': 13,
		'height': 13,
		'icon': './images/mapicons/UrbanLocation.svg',
		'xOffset': 0,
		'yOffset': -2
	},
	'radio': {
		'fontSize': 10,
		'fontWeight': 'bold',
		'fontColor': '#555555',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'location',
		'width': 13,
		'height': 13,
		'icon': './images/mapicons/radio.svg',
		'xOffset': 0,
		'yOffset': -2
	},
	'totalpop': {
		'fontSize': 10,
		'fontWeight': 'bold',
		'fontColor': '#555555',
		'fontFamily': "'Open Sans', sans-serif",
		'fontStyle': 'normal',
		'opacity': 1,
		'symbolClass': 'location',
		'width': 13,
		'height': 13,
		'icon': './images/mapicons/totalpop.svg',
		'xOffset': 0,
		'yOffset': -2
	},
}